color_schemes:
  default:
    roads:
      motorway:
        color: '#d5d5d5'
        linewidth: 1.2
      trunk:
        color: '#d5d5d5'
        linewidth: 1.0
      primary:
        color: '#ededed'
        linewidth: 0.9
      secondary:
        color: '#ededed'
        linewidth: 0.9
      tertiary:
        color: '#a6a6a6'
        linewidth: 0.5
      residential:
        color: '#a6a6a6'
        linewidth: 0.5
      other:
        color: '#676767'
        linewidth: 0.3
    water:
      color: '#72b1b1'
      linewidth: 1.0
    background: '#061529'
  dark:
    roads:
      motorway:
        color: '#ff9e9e'
        linewidth: 1.2
      trunk:
        color: '#ff9e9e'
        linewidth: 1.2
      primary:
        color: '#ffcac5'
        linewidth: 0.9
      secondary:
        color: '#ffcbb2'
        linewidth: 0.9
      tertiary:
        color: '#d3a5a5'
        linewidth: 0.5
      residential:
        color: '#d3a5a5'
        linewidth: 0.5
      other:
        color: '#9e7c7c'
        linewidth: 0.3
    water:
      color: '#506b75'
      linewidth: 1.0
    background: '#000000'
  pink:
    roads:
      motorway:
        color: '#ff0099'
        linewidth: 1.0
      trunk:
        color: '#ff0099'
        linewidth: 1.0
      primary:
        color: '#ff0099'
        linewidth: 0.7
      secondary:
        color: '#ff0099'
        linewidth: 0.7
      tertiary:
        color: '#ff0099'
        linewidth: 0.5
      residential:
        color: '#ff0099'
        linewidth: 0.5
      other:
        color: '#ff0099'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#2e002e'
  green:
    roads:
      motorway:
        color: '#00ff00'
        linewidth: 1.0
      trunk:
        color: '#00ff00'
        linewidth: 1.0
      primary:
        color: '#00ff00'
        linewidth: 0.7
      secondary:
        color: '#00ff00'
        linewidth: 0.7
      tertiary:
        color: '#00ff00'
        linewidth: 0.5
      residential:
        color: '#00ff00'
        linewidth: 0.5
      other:
        color: '#00ff00'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#003300'
  blue:
    roads:
      motorway:
        color: '#00ccff'
        linewidth: 1.0
      trunk:
        color: '#00ccff'
        linewidth: 1.0
      primary:
        color: '#00ccff'
        linewidth: 0.7
      secondary:
        color: '#00ccff'
        linewidth: 0.7
      tertiary:
        color: '#00ccff'
        linewidth: 0.5
      residential:
        color: '#00ccff'
        linewidth: 0.5
      other:
        color: '#00ccff'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#002233'
  yellow:
    roads:
      motorway:
        color: '#ffff00'
        linewidth: 1.0
      trunk:
        color: '#ffff00'
        linewidth: 1.0
      primary:
        color: '#ffff00'
        linewidth: 0.7
      secondary:
        color: '#ffff00'
        linewidth: 0.7
      tertiary:
        color: '#ffff00'
        linewidth: 0.5
      residential:
        color: '#ffff00'
        linewidth: 0.5
      other:
        color: '#ffff00'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#333300'
  violet:
    roads:
      motorway:
        color: '#ff00ff'
        linewidth: 1.0
      trunk:
        color: '#ff00ff'
        linewidth: 1.0
      primary:
        color: '#ff00ff'
        linewidth: 0.7
      secondary:
        color: '#ff00ff'
        linewidth: 0.7
      tertiary:
        color: '#ff00ff'
        linewidth: 0.5
      residential:
        color: '#ff00ff'
        linewidth: 0.5
      other:
        color: '#ff00ff'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#330033'
  red_gold:
    roads:
      motorway:
        color: '#ff4500'
        linewidth: 1.2
      trunk:
        color: '#ff6347'
        linewidth: 1.2
      primary:
        color: '#ffa500'
        linewidth: 0.9
      secondary:
        color: '#ff8c00'
        linewidth: 0.9
      tertiary:
        color: '#ffd700'
        linewidth: 0.5
      residential:
        color: '#ffd700'
        linewidth: 0.5
      other:
        color: '#ffd9b3'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#2b1b17'
  midnight_teal:
    roads:
      motorway:
        color: '#00ced1'
        linewidth: 1.2
      trunk:
        color: '#48d1cc'
        linewidth: 1.2
      primary:
        color: '#20b2aa'
        linewidth: 0.9
      secondary:
        color: '#5f9ea0'
        linewidth: 0.9
      tertiary:
        color: '#4682b4'
        linewidth: 0.5
      residential:
        color: '#87ceeb'
        linewidth: 0.5
      other:
        color: '#708090'
        linewidth: 0.3
    water:
      color: '#00ffff'
      linewidth: 1.0
    background: '#101820'
  ice_fire:
    roads:
      motorway:
        color: '#ff4500'
        linewidth: 1.2
      trunk:
        color: '#ff6347'
        linewidth: 1.2
      primary:
        color: '#ffa500'
        linewidth: 0.9
      secondary:
        color: '#ffcccb'
        linewidth: 0.9
      tertiary:
        color: '#add8e6'
        linewidth: 0.5
      residential:
        color: '#87ceeb'
        linewidth: 0.5
      other:
        color: '#4682b4'
        linewidth: 0.3
    water:
      color: '#1e90ff'
      linewidth: 1.0
    background: '#202020'
  copper_twilight:
    roads:
      motorway:
        color: '#b87333'
        linewidth: 1.2
      trunk:
        color: '#cd853f'
        linewidth: 1.2
      primary:
        color: '#daa520'
        linewidth: 0.9
      secondary:
        color: '#a0522d'
        linewidth: 0.9
      tertiary:
        color: '#ffebcd'
        linewidth: 0.5
      residential:
        color: '#deb887'
        linewidth: 0.5
      other:
        color: '#8b4513'
        linewidth: 0.3
    water:
      color: '#4682b4'
      linewidth: 1.0
    background: '#2e1a14'
  solar_flare:
    roads:
      motorway:
        color: '#ffff33'
        linewidth: 1.2
      trunk:
        color: '#ffa500'
        linewidth: 1.2
      primary:
        color: '#ff4500'
        linewidth: 0.9
      secondary:
        color: '#ff6347'
        linewidth: 0.9
      tertiary:
        color: '#ffd700'
        linewidth: 0.5
      residential:
        color: '#ffd700'
        linewidth: 0.5
      other:
        color: '#ffa07a'
        linewidth: 0.3
    water:
      color: '#4169e1'
      linewidth: 1.0
    background: '#202020'
  emerald_glow:
    roads:
      motorway:
        color: '#50c878'
        linewidth: 1.2
      trunk:
        color: '#32cd32'
        linewidth: 1.2
      primary:
        color: '#228b22'
        linewidth: 0.9
      secondary:
        color: '#98fb98'
        linewidth: 0.9
      tertiary:
        color: '#90ee90'
        linewidth: 0.5
      residential:
        color: '#8fbc8f'
        linewidth: 0.5
      other:
        color: '#556b2f'
        linewidth: 0.3
    water:
      color: '#87ceeb'
      linewidth: 1.0
    background: '#003333'
  nebula_dream:
    roads:
      motorway:
        color: '#ff1493'
        linewidth: 1.2
      trunk:
        color: '#ff69b4'
        linewidth: 1.2
      primary:
        color: '#8a2be2'
        linewidth: 0.9
      secondary:
        color: '#9370db'
        linewidth: 0.9
      tertiary:
        color: '#ba55d3'
        linewidth: 0.5
      residential:
        color: '#dda0dd'
        linewidth: 0.5
      other:
        color: '#9400d3'
        linewidth: 0.3
    water:
      color: '#00ced1'
      linewidth: 1.0
    background: '#1a0033'
  neon_pink:
    roads:
      motorway:
        color: '#ff1493'
        linewidth: 1.2
      trunk:
        color: '#ff69b4'
        linewidth: 1.2
      primary:
        color: '#ff85c0'
        linewidth: 0.9
      secondary:
        color: '#ff99cc'
        linewidth: 0.9
      tertiary:
        color: '#ffb3e6'
        linewidth: 0.5
      residential:
        color: '#ffe6f7'
        linewidth: 0.5
      other:
        color: '#ff007f'
        linewidth: 0.3
    water:
      color: '#0077ff'
      linewidth: 1.0
    background: '#330033'
  default_thinned:
    roads:
      motorway:
        color: '#d5d5d5'
        linewidth: 2.2
      trunk:
        color: '#d5d5d5'
        linewidth: 1.8
      primary:
        color: '#ededed'
        linewidth: 1.4
      secondary:
        color: '#ededed'
        linewidth: 1.0
      tertiary:
        color: '#a6a6a6'
        linewidth: 0.6
      residential:
        color: '#a6a6a6'
        linewidth: 0.3
      other:
        color: '#676767'
        linewidth: 0.2
    water:
      color: '#72b1b1'
      linewidth: 1.0
    background: '#061529'
  default_hierarchized:
    roads:
      motorway:
        color: '#ffffff'
        linewidth: 2.5
      trunk:
        color: '#cccccc'
        linewidth: 2.0
      primary:
        color: '#bbbbbb'
        linewidth: 1.6
      secondary:
        color: '#999999'
        linewidth: 1.2
      tertiary:
        color: '#777777'
        linewidth: 0.8
      residential:
        color: '#555555'
        linewidth: 0.4
      other:
        color: '#333333'
        linewidth: 0.2
    water:
      color: '#72b1b1'
      linewidth: 1.0
    background: '#061529'
